import type { Property } from '@/types/property'

export const mockProperties: Property[] = [
  {
    id: '1',
    title: 'Departamento moderno en Palermo',
    description: 'Hermoso departamento a estrenar con amenities completos. Amplio living comedor, cocina integrada, dormitorio en suite con vestidor y balcón corrido con vista a la ciudad.',
    type: 'departamento',
    operation: 'venta',
    price: 120000,
    currency: 'USD',
    surface: 85,
    rooms: 3,
    bathrooms: 1,
    parking: 1,
    address: 'Thames 1234',
    neighborhood: 'Palermo',
    city: 'Buenos Aires',
    province: 'Buenos Aires',
    lat: -34.5885,
    lng: -58.4324,
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800'],
    has360Tour: true,
    aiMatchScore: 94,
    features: ['pileta', 'gimnasio', 'parrilla', 'seguridad 24hs'],
    agencyId: 'agency-1',
    agentId: 'agent-1',
    createdAt: '2025-01-01',
    updatedAt: '2025-01-01',
  },
  {
    id: '2',
    title: 'Casa con jardín en Belgrano',
    description: 'Espléndida casa de dos plantas en barrio residencial. Jardín con pileta, quincho y parrilla. Ideal para familias que buscan tranquilidad sin alejarse de la ciudad.',
    type: 'casa',
    operation: 'venta',
    price: 285000,
    currency: 'USD',
    surface: 220,
    rooms: 4,
    bathrooms: 3,
    parking: 2,
    address: 'Juramento 2500',
    neighborhood: 'Belgrano',
    city: 'Buenos Aires',
    province: 'Buenos Aires',
    lat: -34.5618,
    lng: -58.4558,
    images: ['https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800'],
    has360Tour: false,
    aiMatchScore: 87,
    features: ['pileta', 'parrilla', 'jardín', 'quincho'],
    agencyId: 'agency-1',
    agentId: 'agent-2',
    createdAt: '2025-01-05',
    updatedAt: '2025-01-05',
  },
  {
    id: '3',
    title: 'Departamento en alquiler - Recoleta',
    description: 'Luminoso departamento piso 8 con vista abierta. Totalmente amoblado y equipado. A pasos del Cementerio de la Recoleta y las mejores galerías de arte.',
    type: 'departamento',
    operation: 'alquiler',
    price: 450000,
    currency: 'ARS',
    surface: 60,
    rooms: 2,
    bathrooms: 1,
    parking: 0,
    address: 'Av. Callao 1100',
    neighborhood: 'Recoleta',
    city: 'Buenos Aires',
    province: 'Buenos Aires',
    lat: -34.5885,
    lng: -58.3937,
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800'],
    has360Tour: true,
    aiMatchScore: 78,
    features: ['balcón', 'seguridad 24hs', 'lavadero'],
    agencyId: 'agency-2',
    agentId: 'agent-3',
    createdAt: '2025-01-10',
    updatedAt: '2025-01-10',
  },
  {
    id: '4',
    title: 'Casa quinta en Córdoba Capital',
    description: 'Amplia casa quinta a minutos del centro cordobés. Terreno de 800m², pileta, parrilla y espacios verdes. Ideal para invertir o como residencia permanente.',
    type: 'casa',
    operation: 'venta',
    price: 195000,
    currency: 'USD',
    surface: 180,
    rooms: 4,
    bathrooms: 2,
    parking: 2,
    address: 'Av. Colón 3400',
    neighborhood: 'Alta Córdoba',
    city: 'Córdoba',
    province: 'Córdoba',
    lat: -31.4201,
    lng: -64.1888,
    images: ['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800'],
    has360Tour: false,
    aiMatchScore: 82,
    features: ['pileta', 'parrilla', 'jardín', 'área de juegos'],
    agencyId: 'agency-3',
    agentId: 'agent-4',
    createdAt: '2025-01-12',
    updatedAt: '2025-01-12',
  },
  {
    id: '5',
    title: 'Oficina premium en Rosario',
    description: 'Modernas oficinas clase A en el corredor financiero de Rosario. Piso completo con salas de reuniones, recepción equipada y terraza privada. Ideal para empresas en crecimiento.',
    type: 'oficina',
    operation: 'alquiler',
    price: 850000,
    currency: 'ARS',
    surface: 150,
    rooms: 6,
    bathrooms: 2,
    parking: 3,
    address: 'Córdoba 1850 Piso 12',
    neighborhood: 'Centro',
    city: 'Rosario',
    province: 'Santa Fe',
    lat: -32.9468,
    lng: -60.6393,
    images: ['https://images.unsplash.com/photo-1497366216548-37526070297c?w=800'],
    has360Tour: true,
    aiMatchScore: 71,
    features: ['terraza', 'seguridad 24hs', 'cochera'],
    agencyId: 'agency-4',
    agentId: 'agent-5',
    createdAt: '2025-01-15',
    updatedAt: '2025-01-15',
  },
  {
    id: '6',
    title: 'Departamento de lujo en Mendoza',
    description: 'Exclusivo departamento en el barrio más valorizado de Mendoza. Vistas a la cordillera, acabados de primera línea y complejo con todas las amenidades premium.',
    type: 'departamento',
    operation: 'venta',
    price: 165000,
    currency: 'USD',
    surface: 110,
    rooms: 3,
    bathrooms: 2,
    parking: 1,
    address: 'Mitre 456',
    neighborhood: 'Ciudad',
    city: 'Mendoza',
    province: 'Mendoza',
    lat: -32.8908,
    lng: -68.8272,
    images: ['https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800'],
    has360Tour: true,
    aiMatchScore: 89,
    features: ['pileta', 'gimnasio', 'parrilla', 'seguridad 24hs', 'bodega'],
    agencyId: 'agency-5',
    agentId: 'agent-6',
    createdAt: '2025-01-18',
    updatedAt: '2025-01-18',
  },
]
